### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mdesantis** [atom/find-and-replace#1080]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Searching for a string with many matches **AND providing a file/directory pattern** (I searched for `create` in a clone of [this repository](https://github.com/solidusio/solidus) specifying `core/spec` as file/directory pattern, Finding with Options: No regex search, Case Sensitive | Case Insensitive (I tried both), No Whole Word) produces the following error:

```
Uncaught RangeError: Maximum call stack size exceeded

At /usr/share/atom/resources/app/static/<embedded>:14

RangeError: Maximum call stack size exceeded
    at ResultRowGroup.generateRows (/usr/share/atom/resources/app/static/<embedded>:14:2345380)
    at new ResultRowGroup (/usr/share/atom/resources/app/static/<embedded>:14:2344410)
    at ResultsView.didAddResult (/usr/share/atom/resources/app/static/<embedded>:14:549573)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1189979)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191420)
    at ResultsModel.addResult (/usr/share/atom/resources/app/static/<embedded>:11:793346)
    at ResultsModel.setResult (/usr/share/atom/resources/app/static/<embedded>:11:793234)
    at inProgressSearchPromise.atom.workspace.scan (/usr/share/atom/resources/app/static/<embedded>:11:790989)
    at didMatch (/usr/share/atom/resources/app/static/<embedded>:11:440043)
    at /usr/share/atom/resources/app/static/<embedded>:14:37649
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1189979)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191420)
    at ChildProcess.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:36762)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Steps to Reproduce

1. `git clone https://github.com/solidusio/solidus`
2. `atom solidus`
3. Open Find and Replace dialog
4. type `create` in the search input
5. type `core/spec` in File/directory pattern input (**required: if I leave directory/file pattern unset the error does not raise up**)
6. Press Find All

**Expected behavior:** the search provides the results without raising any errors

**Actual behavior:** the search raise the error above

**Reproduces how often:** 100%

### Versions

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04.2
```
> apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 3.7.2
git 2.21.0
```

### Additional Information

Notice that **if I leave directory/file pattern unset the error does not raise up**: in order the error to raise up I have to specify `core/spec` as file/directory pattern

<details>
 <summary>Error log</summary>

 [Enter steps to reproduce:]

 1. ...
 2. ...

 **Atom**: 1.36.1 x64
 **Electron**: 2.0.18
 **OS**: Ubuntu 18.04.2
 **Thrown From**: Atom Core

 ### Stack Trace

 Uncaught RangeError: Maximum call stack size exceeded

 ```
 At /usr/share/atom/resources/app/static/<embedded>:14

 RangeError: Maximum call stack size exceeded
     at ResultRowGroup.generateRows (/usr/share/atom/resources/app/static/<embedded>:14:2345380)
     at new ResultRowGroup (/usr/share/atom/resources/app/static/<embedded>:14:2344410)
     at ResultsView.didAddResult (/usr/share/atom/resources/app/static/<embedded>:14:549573)
     at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1189979)
     at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191420)
     at ResultsModel.addResult (/usr/share/atom/resources/app/static/<embedded>:11:793346)
     at ResultsModel.setResult (/usr/share/atom/resources/app/static/<embedded>:11:793234)
     at inProgressSearchPromise.atom.workspace.scan (/usr/share/atom/resources/app/static/<embedded>:11:790989)
     at didMatch (/usr/share/atom/resources/app/static/<embedded>:11:440043)
     at /usr/share/atom/resources/app/static/<embedded>:14:37649
     at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1189979)
     at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191420)
     at ChildProcess.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:36762)
     at emitTwo (events.js:126:13)
     at ChildProcess.emit (events.js:214:7)
     at emit (internal/child_process.js:772:12)
     at _combinedTickCallback (internal/process/next_tick.js:141:11)
     at process._tickCallback (internal/process/next_tick.js:180:9)
 ```

 ### Commands

 ```
      -5:42.1.0 project-find:show (input.hidden-input)
   2x -5:40 core:confirm (input.hidden-input)
      -2:34.1.0 project-find:show (div.results-view.focusable-panel)
      -2:24.1.0 core:confirm (input.hidden-input)
 ```

 ### Non-Core Packages

 ```

 ```

</details>

**Comment by mdesantis** [comment]
The issue is marked by Atom as already reported on core: https://github.com/atom/atom/issues/4767 but I thought it was better to report it here

**Comment by Blondemonk** [comment]
I've also hit this issue, running Ubuntu 19.10 and Atom 1.42.0. In my case, it seems that the search completes (the search shows that >30,000 results in 48 files), but it only shows the first two previews before erroring - it seems that the second preview is for a file containing 29,356 matches.

I installed the .deb from atom.io. 
```
> apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.42.0
python 2.7.17
git 2.20.1
```
