### ISSUE TITLE
Sometimes I got Uncaught RangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by ghost** [atom/find-and-replace#216]
I got Uncaught RangeError: Maximum call stack size exceeded  and cannot modify any element.

What is the reason behind?

**Comment by monje** [comment]
I just received a similar error when working on a large file; approximately 41k lines. Atom tells me:

> *The error was thrown from the find-and-replace package. This issue has already been reported.*

And shows the following stack trace:
~~~
RangeError: Maximum call stack size exceeded
    at BufferSearch.module.exports.BufferSearch.bufferStoppedChanging (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:248:52)
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1321:25
~~~

**Comment by monje** [comment]
After a little more investigation, I've found that this error can be triggered by using the atom-beautify package to beautify a 41k line JSON file.

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.194.0

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:248

RangeError: Maximum call stack size exceeded
    at BufferSearch.module.exports.BufferSearch.bufferStoppedChanging (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:248:52)
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1321:25
```

### Commands

```
     -9:52.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -9:48.9.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/monje/Development",
    "disabledPackages": [
      "autocomplete-haskell",
      "sort-lines"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.21
color-picker, v2.1.0
json-converter, v0.2.4
language-docker, v1.1.6
language-haskell, v1.5.2
language-latex, v0.6.1
language-mongodb, v0.3.1
lines, v0.13.1
minimap, v4.19.0
monokai, v0.18.0

# Dev
No dev packages
```

**Comment by pointmatic** [comment]
Not sure why this is closed. I get consistent crashing on a file with 265K lines of short JSON objects each line about 60 characters, formatted like {"key1":"value1","key2":"value2"}. First crash occurred after the following steps: 1) open file, 2) highlight 9 characters at the beginning of first line, 3) key shortcut for Find, 4) click Replace All. Caused "Uncaught Range Error" and presented link to this bug.

Running stock Atom 1.8 with no modification on Mac 10.11.5
