### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by xdumaine** [atom/find-and-replace#330]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.152.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project-find-view.js:424

TypeError: undefined is not a function
  at ProjectFindView.module.exports.ProjectFindView.search (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project-find-view.js:424:36)
  at ProjectFindView.module.exports.ProjectFindView.confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project-find-view.js:406:28)
  at space-pen-div.subscriptions.add.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project-find-view.js:227:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by parabolic** [comment]
Same here, cannot do a directory search after the atom update.

Atom Version 0.199.0 (0.199.0).
Os: Yosemite 10.10.3

Happens when I try to do a directory search every time.

**Comment by mnquintana** [comment]
@parabolic Can you reproduce this in safe mode (`atom --safe`)?

**Comment by parabolic** [comment]
@mnquintana  Yes, I started it in safe mode, I've noticed that I actually need to do the search in order to get the error. If I don't press enter It works, after I press enter ( do the search ) next search dir click yields this error.
`
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/project-find-view.js:503
Hide Stack Trace
TypeError: undefined is not a function
    at ProjectFindView.module.exports.ProjectFindView.findInCurrentlySelectedDirectory (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/project-find-view.js:503:36)
    at atom-workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find.js:73:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
    at jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:76:67)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
`

Which refers to this bug as well.

THanks.

**Comment by mnquintana** [comment]
@parabolic Does this happen in every project / directory, or only in specific projects?

**Comment by parabolic** [comment]
@mnquintana Yes, it's still open in safe mode and I tried normal dirs and git managed dirs as well.

**Comment by danShumway** [comment]
I'm semi-regularly running into this as well, will start paying attention to actions surrounding when it occurs.  What seems to be the trigger atm for me is searching within a specific directory 
((?something?) - right click on sidebar - select Search in Directory - error triggers - can still enter term and search in directory)

**Comment by yuvilio** [comment]
Can report similar issue to @danShumway . Version: 0.200.0 on Linux.

**Comment by parabolic** [comment]
Hi, any update ? I really miss this feature ...

**Comment by Poyoman39** [comment]
Hi,

Similar problem but only when i right click on left panel, and i choose search in directory.

**Atom Version**: 0.200.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.166.0


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\...\Atom\resources\app.asar\node_modules\find-and-replace\lib\project-find-view.js:507

TypeError: undefined is not a function
  at ProjectFindView.module.exports.ProjectFindView.findInCurrentlySelectedDirectory

**Comment by parabolic** [comment]
Just a quick update, 
I don't have the problem anymore. My atom version is Version 0.201.0 (0.201.0) on Mac Osx Yosemite. 
Cheers.

**Comment by yuvilio** [comment]
Ditto for me. Just upgraded via the Linux ppa to Atom version 0.201.0 and right click on directory->Search in Directory works every time (not just the first).

**Comment by MarkehMe** [comment]
I got this issue by Right clicking on project -> Search in directory. I can still search though, the error just pops up. 

I'm on Atom 0.200.0.

**Comment by gpupo** [comment]
Same here on Atom 0.200.0 and Mac Osx Yosemite

**Comment by r-wettstaedt** [comment]
For me this issue happened in the Keybindings menu of the settings. Focus the "Search keybinding" Input and press [cmd]+[e] (with default keybindings).

Atom 1.0.0

**Comment by izuzak** [comment]
Great -- thanks for the details, @r-wettstaedt, I was able to reproduce this.

cc @benogle

**Comment by RaymondCrandall** [comment]
I am aware ATOM has trouble with large files, and the directory I was searching has large files in it. Perhaps searching directories with large files causes the crash? Looks like I will need to restart the ATOM editor in order to search for anything, now that the find-and-replace module died in the process :'(
