### ISSUE TITLE
Uncaught TypeError: Unable to watch path

### ISSUE THREAD

**Issue by jasonmit** [atom/find-and-replace#345]
1. Attempt to open any file using the tree view navigator

**Atom Version**: 0.174.0
**System**: linux 3.16.0-29-generic
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.156.0

### Stack Trace

Uncaught TypeError: Unable to watch path

```
At /usr/share/atom/resources/app/src/workspace.js:504

TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:399:109)
  at File.module.exports.File.willAddSubscription (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:108:14)
  at File.willAddSubscription (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:3:61)
  at File.module.exports.File.onDidChange (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:88:12)
  at TextBuffer.module.exports.TextBuffer.subscribeToFile (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1089:44)
  at TextBuffer.module.exports.TextBuffer.setPath (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:281:14)
  at new TextBuffer (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:100:14)
  at Project.module.exports.Project.buildBuffer (/usr/share/atom/resources/app/src/project.js:369:16)
  at Project.module.exports.Project.bufferForPath (/usr/share/atom/resources/app/src/project.js:342:63)
  at Project.module.exports.Project.open (/usr/share/atom/resources/app/src/project.js:296:19)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app/src/workspace.js:492:31)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:418:19)
  at MatchView.module.exports.MatchView.confirm (/usr/share/atom/resources/app/node_modules/find-and-replace/lib/project/match-view.js:92:29)
  at space-pen-li.<anonymous> (/usr/share/atom/resources/app/node_modules/find-and-replace/lib/project/results-view.js:47:18)
  at space-pen-ol.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ol.elemData.handle (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -1:39.5 core:backspace (atom-text-editor.editor)
     -1:37.0 core:save (atom-text-editor.editor)
     -0:01.7 project-find:show (atom-text-editor.editor)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "open-on-github",
      "background-tips",
      "metrics"
    ],
    "themes": [
      "atom-dark-ui-slim",
      "monokai"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-dark-ui-slim, v0.47.1
file-icons, v1.4.8
monokai, v0.11.0
space-tab, v0.1.0
travis-ci-status, v0.11.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by benogle** [comment]
This error sucks. Right now, we dont have a good solution other than increasing the watch size: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path
