### ISSUE TITLE
Uncaught TypeError: Cannot read property 'global' of null

### ISSUE THREAD

**Issue by MikeMcElroy** [atom/find-and-replace#373]
[Enter steps to reproduce below:]

1. Pretty much any time I type in a file now.  Makes Atom pretty aggravating to use.

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.156.0

### Stack Trace

Uncaught TypeError: Cannot read property 'global' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:752

TypeError: Cannot read property 'global' of null
  at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:752:21)
  at TextBuffer.module.exports.TextBuffer.scan (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:727:19)
  at TextEditor.module.exports.TextEditor.scan (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2208:26)
  at ResultsModel.module.exports.ResultsModel.onContentsModified (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-model.js:355:14)
  at ResultsModel.onContentsModified (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-model.js:3:61)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-model.js:44:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1151:25

```

### Commands

```
     -3:11.7 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -3:04.1 core:confirm (atom-text-editor.editor.mini)
     -2:05.7 core:select-up (atom-text-editor.editor)
     -2:05.4 core:backspace (atom-text-editor.editor)
     -2:04.8 find-and-replace:show (atom-text-editor.editor)
     -2:03.6 core:confirm (atom-text-editor.editor.mini)
     -2:00.4 core:select-up (atom-text-editor.editor)
     -2:00.1 core:backspace (atom-text-editor.editor)
     -1:56.9 find-and-replace:show (atom-text-editor.editor)
  4x -1:54.4 core:confirm (atom-text-editor.editor.mini)
     -1:42.7 core:save (atom-text-editor.editor)
     -1:26.6 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -1:22.8 core:confirm (atom-text-editor.editor.mini)
  2x -0:04.9 core:backspace (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-lint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v1.5.0
atom-python-debugger, v0.2.2
autocomplete-plus, v2.1.6
jshint, v1.3.0
language-clojure, v0.13.0
linter-clojure, v0.0.4
linter-flake8, v1.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by MikeMcElroy** [comment]
I was a few versions behind, so updating to 0.188 seems to have resolved it.

**Comment by ehtb** [comment]
This just started appearing on almost every file I am editing. The same error message, but a different line number (697):

```
Uncaught TypeError: Cannot read property 'global' of null
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:697
```

Version: 0.194.0

Community packages:
* atom-beautify
* sync-settings
* autocomplete-ruby
* editorconfig
* language-jade
* linter
* linter-eslint
* autocomplete-plus
* linter-css-lint

**Comment by benogle** [comment]
@ehtb can you open a new issue? Can you try safe mode? `atom --safe`

**Comment by ehtb** [comment]
@benogle I have pinpointed the error to a wrongly formatted regular expression (with the reg exp option on). Though the find & replace panel was hidden, the string was still available in the input field. Removing it made the error disappear.

**Comment by sitecareupdater** [comment]
Seeing this issue on the latest version of Atom. Here's the stack trace from a standard text search of an entire project:

**Atom Version**: 1.0.6
**System**: Mac OS X 10.10.4
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.177.0


### Stack Trace

Uncaught TypeError: Cannot read property 'global' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:837

TypeError: Cannot read property 'global' of null
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:837:21)
    at TextBuffer.module.exports.TextBuffer.scan (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:812:19)
    at TextEditor.module.exports.TextEditor.scan (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2121:26)
    at ResultsModel.module.exports.ResultsModel.onContentsModified (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/project/results-model.js:320:14)
    at ResultsModel.onContentsModified (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/project/results-model.js:3:61)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/project/results-model.js:37:26
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1250:25
```

### Commands

```
     -0:25.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:22.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:22.3.0 core:delete (atom-text-editor.editor.is-focused)
     -0:20.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:20.2.0 core:delete (atom-text-editor.editor.is-focused)
     -0:19.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:16.8.0 project-find:show (atom-text-editor.editor.is-focused)
  2x -0:16.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "one-dark-ui",
      "base16-eighties-one-dark"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
atom-minify, v0.2.2
atom-wordpress, v0.3.0
base16-eighties-one-dark, v0.2.2
docblockr, v0.7.3
esformatter, v1.8.0
file-icons, v1.6.3
highlight-selected, v0.10.1
line-ending-converter, v1.2.0
linter, v1.3.4
linter-csslint, v1.0.5
linter-jscs, v2.0.4
linter-jshint, v1.1.5
linter-jsonlint, v0.1.4
linter-php, v1.0.3
linter-phpcs, v1.0.6
linter-scss-lint, v2.0.0
minimap, v4.12.2
minimap-pigments, v0.1.3
php-debug, v0.1.2
pigments, v0.9.3
project-manager, v1.15.11
sync-settings, v0.6.0
tabs-to-spaces, v0.11.0
trailing-spaces, v0.3.2
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@sitecareupdater Can you please provide the _exact_ steps which reproduce the issue for you after you start Atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? I'm having trouble reproducing this.

**Comment by robneu** [comment]
Whoops, opened that issue from the wrong account. Anyway, in safe mode the steps to reproduce are:

1. Open a project containing PHP files. (Not sure if this is important)
2. Do a `Find in Project` for any string that's recurring in the project
3. Result is that nothing is found regardless of multiple occurrences in the project
4. Edit a file in the project

While editing the file, this error will reoccur over and over again for every keystroke.
![no-results](https://cloud.githubusercontent.com/assets/2184093/9218329/171b0604-4097-11e5-8937-ce6ec6c3973e.png)
![errors](https://cloud.githubusercontent.com/assets/2184093/9218328/1719d52c-4097-11e5-9ede-608101f036bd.png)

**Comment by atalargo** [comment]
+1 same issue, same reproductibility steps

**Comment by izuzak** [comment]
Yeah, I'm able to reproduce this now -- thanks, @robneu @atalargo :bow:. /cc @benogle

**Comment by lukevp** [comment]
Also experiencing this issue in the same way (no results were found, all lines have errors.)

[Enter steps to reproduce below:]

1. Do a Find in Project (no results found)
2. edit file, start typing (happening with a .less file at the moment in an angular app)

**Atom Version**: 1.0.6
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.177.0


### Stack Trace

Uncaught TypeError: Cannot read property 'global' of null

```
At C:\Users\LukeP\AppData\Local\atom\app-1.0.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:837

TypeError: Cannot read property 'global' of null
    at TextBuffer.module.exports.TextBuffer.scanInRange (C:\Users\LukeP\AppData\Local\atom\app-1.0.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:837:21)
    at TextBuffer.module.exports.TextBuffer.scan (C:\Users\LukeP\AppData\Local\atom\app-1.0.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:812:19)
    at TextEditor.module.exports.TextEditor.scan (C:\Users\LukeP\AppData\Local\atom\app-1.0.6\resources\app.asar\src\text-editor.js:2121:26)
    at ResultsModel.module.exports.ResultsModel.onContentsModified (C:\Users\LukeP\AppData\Local\atom\app-1.0.6\resources\app.asar\node_modules\find-and-replace\lib\project\results-model.js:320:14)
    at ResultsModel.onContentsModified (C:\Users\LukeP\AppData\Local\atom\app-1.0.6\resources\app.asar\node_modules\find-and-replace\lib\project\results-model.js:3:61)
    at C:\Users\LukeP\AppData\Local\atom\app-1.0.6\resources\app.asar\node_modules\find-and-replace\lib\project\results-model.js:37:26
    at Emitter.module.exports.Emitter.emit (C:\Users\LukeP\AppData\Local\atom\app-1.0.6\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at C:\Users\LukeP\AppData\Local\atom\app-1.0.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1250:25
```

### Commands

```
     -9:57.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -5:20.6.0 core:delete (atom-text-editor.editor.is-focused)
     -4:50.9.0 core:save (atom-text-editor.editor.is-focused)
     -2:44.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:44.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:11.1.0 project-find:show (atom-text-editor.editor.is-focused)
     -1:07.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:49.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:45.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
compare-files, v0.6.2

# Dev
No dev packages
```

**Comment by lukevp** [comment]
Solution that was posted on atom/atom#8344 worked for me (toggle one of the search options - I toggled Regex on and off)
