### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by carstn** [atom/find-and-replace#415]
[Enter steps to reproduce below:]

1. Find and Replace with the options 'Regex' and 'Case Sensitive'
2. Enter Find text: "return\n"
3. Enter Replace text: "panic(err)\n"
4. Press Replace All.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.174.0

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1098

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1098:15)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:179:33)
  at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:243:36)
  at DisplayBuffer.module.exports.DisplayBuffer.refreshMarkerScreenPositions (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1486:16)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:313:14)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1562:19)
  at Fold.module.exports.Fold.updateDisplayBuffer (/Applications/Atom.app/Contents/Resources/app.asar/src/fold.js:90:35)
  at Fold.module.exports.Fold.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/fold.js:98:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/fold.js:20:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:256:20)
  at Fold.module.exports.Fold.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/fold.js:43:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/fold.js:28:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:400:20)
  at MarkerStore.module.exports.MarkerStore.createSnapshot (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:229:20)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:751:72)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1152:26)
  at BufferSearch.module.exports.BufferSearch.replace (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:91:19)
  at FindView.module.exports.FindView.replaceAll (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:500:29)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:3:61)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  2x -1:21.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:19.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:18.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  4x -1:18 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:13.3.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -1:13.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:12.6.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -1:12.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:09.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:08.7.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -1:08.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:08.2.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
  2x -1:08.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:06.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:25.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  3x -0:19.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".gitignore"
    ],
    "projectHome": "/Users/carstenganske/Code/accusearch",
    "disabledPackages": [
      "vim-mode",
      "javascript-snippets",
      "nuclide-quick-open",
      "nuclide-flow",
      "nuclide-hack",
      "nuclide-type-hint",
      "nuclide-diff-view",
      "nuclide-file-watcher",
      "nuclide-code-format",
      "nuclide-click-to-symbol",
      "nuclide-hg-repository",
      "nuclide-language-hack",
      "nuclide-remote-projects",
      "save-session"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
atom-cli-diff, v1.0.0
go-plus, v3.3.12
go-rename, v0.3.0
go-runtime, v0.2.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
jshint, v1.3.7
language-protobuf, v0.3.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@carstn Can you reliably reproduce this? I just tried following your instructions and wasn't able to reproduce.

**Comment by carstn** [comment]
I'm out of town; I'll test it this weekend.

**Comment by carstn** [comment]
I can't reproduce it now, must've been caused by something else in that session.
