### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by ztolley** [atom/find-and-replace#443]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.174.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getText' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1633

TypeError: Cannot read property 'getText' of undefined
  at TextEditor.module.exports.TextEditor.getSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1633:37)
  at FindView.module.exports.FindView.focusFindEditor (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:373:131)
  at FindView.focusFindEditor (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:3:61)
  at atom-workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find.js:114:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -6:20.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:18.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:18.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -6:18.2.0 core:save (atom-text-editor.editor.is-focused)
     -4:17 core:move-left (atom-text-editor.editor.is-focused)
  5x -4:12.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:09.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.6.0 pane:split-right (atom-text-editor.editor.is-focused)
     -0:04.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:02.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:01.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:01.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:00.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "wrap-guide",
      "whitespace",
      "bracket-matcher"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.0.0
atom-jade, v0.3.0
atom-ternjs, v0.6.8
autocomplete-php, v0.3.6
autocomplete-ruby, v0.1.0
behat-atom, v0.1.2
css-color-underline, v1.0.1
editorconfig, v1.0.1
language-puppet, v0.12.0
linter, v1.2.3
linter-phpcs, v1.0.4
php-twig, v4.0.0
seti-syntax, v0.4.0
seti-ui, v0.7.1
symfony-snippets, v0.3.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
Weird. Can you remember what you had in the find box?
