### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by anatooly** [atom/find-and-replace#444]
[Enter steps to reproduce below:]
1. Search text in folder on large project

**Atom Version**: 1.0.2
**System**: elementary OS
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.174.2
### Stack Trace

Uncaught RangeError: Invalid string length

```
At /usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:310

RangeError: Invalid string length
  at Array.join (native)
  at ReadStream.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:310:43)
  at emitNone (events.js:72:20)
  at ReadStream.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at Object.RemoteMemberFunction [as showMessageBox] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at Atom.module.exports.Atom.confirm (/usr/share/atom/resources/app.asar/src/atom.js:729:23)
  at Project.module.exports.Project.open (/usr/share/atom/resources/app.asar/src/project.js:382:23)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:449:31)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:375:19)
  at MatchView.module.exports.MatchView.confirm (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/project/match-view.js:92:29)
  at space-pen-li.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/project/results-view.js:47:18)
  at space-pen-ol.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ol.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -8:12 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -8:11.8.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -8:11.2.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -7:56.2.0 core:save (atom-text-editor.editor.is-focused)
  3x -7:32.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:28.3.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -7:27.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:27.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  3x -7:26.7.0 core:save (atom-text-editor.editor.is-focused)
     -7:14.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 12x -6:42.3.0 core:copy (atom-text-editor.editor.is-focused)
     -4:19.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -4:19.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:16.5.0 project-find:show (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -4:14.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -4:14.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
javascript-snippets, v1.0.0
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by benogle** [comment]
Looks like this was when opening a file from the results view. Is that correct? Or did it show up while searching and no user input?

**Comment by rsese** [comment]
Going to go ahead and close in favor of a more recent and similar report /cc https://github.com/atom/find-and-replace/issues/869.
