### ISSUE TITLE
when running on mounted sshfs folder : RegExp to big.

### ISSUE THREAD

**Issue by arwidt** [atom/find-and-replace#532]
After atom update 1.0.13 whole module stopped working, there was no problem before the update.

////////////////////////////// ERROR MESSAGE BELOW

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.181.0

### Stack Trace

Failed to activate the find-and-replace package

```
At Invalid regular expression: /

////////////////
removed file content
////////////////

 /: RegExp too big
    at RegExp.exec (native)
    at Forwards.next (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/match-iterator.js:15:30)
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:861:31)
    at TextEditor.module.exports.TextEditor.scanInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2143:26)
    at BufferSearch.module.exports.BufferSearch.createMarkers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:155:23)
    at BufferSearch.module.exports.BufferSearch.recreateMarkers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:140:26)
    at BufferSearch.module.exports.BufferSearch.setEditor (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:63:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find.js:65:36
    at PaneContainer.module.exports.PaneContainer.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:140:7)
    at Workspace.module.exports.Workspace.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:294:33)
```

### Commands

```
     -0:02.5.0 project-find:show (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-objective-c",
      "language-ruby",
      "language-ruby-on-rails",
      "metrics",
      "sync-settings",
      "remote-sync"
    ]
  },
  "find-and-replace": {}
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
autoclose-html, v0.19.0
html-entities, v0.4.0
php-twig, v4.0.0
pigments, v0.15.0
pretty-json, v0.4.1
tab-close-double-click, v1.0.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Did you accidentally copy/paste the entire file into the Find and Replace box?

**Comment by arwidt** [comment]
Hello again.

It seems like the error is because the searchfield gets a very big string. But I do not have a file in my clipboard.

The steps I take to reproduce are:

1. mount a external disk with sshfs. https://medium.com/@gsklee/atom-working-with-remote-files-seamlessly-over-ssh-using-sshfs-38de3b31965f

2. open mounted project with cmd: atom -n .

3. make sure there is a small string in clipboard.

4. press cmd+shift+s to open the project search.

5. I get the error.

Hope this helps.
