### ISSUE TITLE
Uncaught TypeError: pane.onDidMoveItem is not a function

### ISSUE THREAD

**Issue by MoOx** [atom/find-and-replace#545]
1. open find and replace
2. search
3. boom

Note that the 2nd time, it works without error.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.181.0

### Stack Trace

Uncaught TypeError: pane.onDidMoveItem is not a function

```
At /Users/MoOx/Sync/Development/atom/smart-tab-name/lib/smart-tab-name.coffee:119

TypeError: pane.onDidMoveItem is not a function
  at /Users/MoOx/Sync/Development/atom/smart-tab-name/lib/smart-tab-name.coffee:119:27
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.didAddPane (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane-container.js:288:27)
  at Pane.module.exports.Pane.setContainer (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:100:26)
  at PaneAxis.module.exports.PaneAxis.addChild (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:142:13)
  at PaneAxis.module.exports.PaneAxis.insertChildAfter (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:214:19)
  at Pane.module.exports.Pane.split (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:720:23)
  at Pane.module.exports.Pane.splitRight (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:686:19)
  at Pane.module.exports.Pane.findOrCreateRightmostSibling (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:750:21)
  at Workspace.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:373:43)
  at Workspace.module.exports.Workspace.open (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:377:12)
  at ProjectFindView.module.exports.ProjectFindView.showResultPane (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/project-find-view.js:556:29)
  at ProjectFindView.module.exports.ProjectFindView.search (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/project-find-view.js:469:19)
  at ProjectFindView.module.exports.ProjectFindView.confirm (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/project-find-view.js:449:28)
  at space-pen-div.subscriptions.add.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/project-find-view.js:265:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -1:41.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:40.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:40.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:40.2.0 core:paste (atom-text-editor.editor.is-focused)
     -1:39.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:17.3.0 core:close (atom-text-editor.editor.is-focused)
     -1:16.4.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -1:15.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -1:14.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -1:14.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:13.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:08.8.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -1:04.5.0 core:close (atom-text-editor.editor.is-focused)
     -0:03.5.0 project-find:show (atom-text-editor.editor.is-focused)
     -0:03.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:02.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/MoOx/Sync/Development",
    "disabledPackages": [
      "language-mustache",
      "welcome",
      "language-toml",
      "language-sass",
      "language-ruby-on-rails",
      "language-ruby",
      "language-python",
      "language-perl",
      "language-objective-c",
      "language-java",
      "language-hyperlink",
      "language-go",
      "language-csharp",
      "language-clojure",
      "language-jsx",
      "close-tags"
    ]
  },
  "find-and-replace": {
    "openProjectFindResultsInRightPane": true,
    "focusEditorAfterSearch": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
atom-color-highlight, v3.0.8
auto-update-packages, v1.0.0
bezier-curve-editor, v0.7.2
break-time, v0.2.0
color-picker, v2.0.12
docblockr, v0.7.3
editorconfig, v1.2.0
file-type-icons, v0.7.3
git-log, v0.4.1
git-tab-status, v1.7.0
language-apache, v1.3.0
linter, v1.8.0
linter-eslint, v3.1.0
linter-jsonlint, v1.0.1
live-archive, v0.1.15
pigments, v0.15.0
project-manager, v2.6.1
react, v0.12.10
smart-tab-name, v1.0.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@MoOx this looks like it's caused by your own `smart-tab-name` package :wink:.
`At /Users/MoOx/Sync/Development/atom/smart-tab-name/lib/smart-tab-name.coffee:119`

**Comment by MoOx** [comment]
Oups... Sorryy !
