### ISSUE TITLE
Uncaught TypeError: this.editor.scanInBufferRange is not a function

### ISSUE THREAD

**Issue by Fannon** [atom/find-and-replace#582]
This happens with the https://github.com/markushedvall/plantuml-viewer package installed, after I've used find/replace once. This keeps appearing even after find/replace is closed again.

**Atom Version**: 1.1.0
**System**: FANNON-WORK
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.185.0
### Stack Trace

Uncaught TypeError: this.editor.scanInBufferRange is not a function

```
At C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\find-and-replace\lib\buffer-search.js:155

TypeError: this.editor.scanInBufferRange is not a function
  at BufferSearch.module.exports.BufferSearch.createMarkers (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\find-and-replace\lib\buffer-search.js:155:23)
  at BufferSearch.module.exports.BufferSearch.recreateMarkers (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\find-and-replace\lib\buffer-search.js:140:26)
  at BufferSearch.module.exports.BufferSearch.setEditor (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\find-and-replace\lib\buffer-search.js:63:19)
  at C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\find-and-replace\lib\find.js:69:36
  at Emitter.module.exports.Emitter.emit (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:333:27
  at Pane.module.exports.Pane.observeActiveItem (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:195:7)
  at C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:331:42
  at Emitter.module.exports.Emitter.emit (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at PaneContainer.module.exports.PaneContainer.setActivePane (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-container.js:196:22)
  at Pane.module.exports.Pane.activate (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:616:15)
  at space-pen-div.<anonymous> (C:\Users\Fannon\.atom\packages\plantuml-viewer\lib\plantuml-viewer-view.js:43:48)
  at space-pen-div.jQuery.event.dispatch (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-div.elemData.handle (C:\Users\Fannon\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```
### Commands

```
     -1:58.9.0 core:copy (atom-text-editor.editor.is-focused)
     -1:56.2.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:52.7.0 core:undo (atom-text-editor.editor.is-focused)
  2x -1:50.1.0 core:paste (atom-text-editor.editor.is-focused)
     -1:45.3.0 core:copy (atom-text-editor.editor.is-focused)
     -1:44.5.0 core:paste (atom-text-editor.editor.is-focused)
     -1:37.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:35.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:35.7.0 editor:upper-case (atom-text-editor.editor)
     -1:29.6.0 core:copy (atom-text-editor.editor.is-focused)
     -1:00.6.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:56.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:51.9.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:33 core:copy (atom-text-editor.editor.is-focused)
     -0:16.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:15.8.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.16
atom-handlebars, v1.2.0
atom-pair, v2.0.10
color-picker, v2.0.13
emmet, v2.3.13
language-mediawiki, v2.0.0
language-plantuml, v0.1.1
linter, v1.10.0
linter-js-yaml, v1.2.0
linter-markdown, v1.2.1
linter-php, v1.0.5
linter-sass-lint, v0.4.1
minimap, v4.16.0
minimap-git-diff, v4.1.8
minimap-linter, v1.0.0
nucleus-dark-ui, v0.6.6
pigments, v0.18.1
plantuml-viewer, v0.7.0

# Dev
No dev packages
```

**Comment by asbjornu** [comment]
This is still happening in Atom 1.4.3

**Comment by wenslayer** [comment]
And with Atom 1.5.3. (Hi @kevinsawicki!)

**Comment by alfechner** [comment]
Confirm 1.5.3.
