### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedBufferRanges' of null

### ISSUE THREAD

**Issue by jormar** [atom/find-and-replace#619]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.0
**System**: Ubuntu 14.04.3
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.194.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRanges' of null

```
At /usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find-view.js:788

TypeError: Cannot read property 'getSelectedBufferRanges' of null
    at FindView.module.exports.FindView.anyMarkersAreSelected (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find-view.js:788:36)
    at FindView.anyMarkersAreSelected (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find-view.js:3:61)
    at FindView.module.exports.FindView.toggleCaseOption (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find-view.js:808:17)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/find-and-replace/lib/find-view.js:3:61)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:45.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.3.0 find-and-replace:show (div.panels)
  2x -0:24 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:23.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:19.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:19.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:18.6.0 find-and-replace:show (atom-text-editor.editor.mini.is-focused)
     -0:17.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:17.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:16.3.0 find-and-replace:show (atom-text-editor.editor.mini.is-focused)
     -0:14.5.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -0:13.5.0 find-and-replace:focus-previous (atom-text-editor.editor.mini.is-focused)
     -0:12.2.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -0:11.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.8
linter, v1.11.3

# Dev
No dev packages
```

**Comment by mrwedders** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Mac OS X 10.10.5
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.194.0


### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRanges' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:788

TypeError: Cannot read property 'getSelectedBufferRanges' of null
    at FindView.module.exports.FindView.anyMarkersAreSelected (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:788:36)
    at FindView.anyMarkersAreSelected (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:3:61)
    at FindView.module.exports.FindView.toggleCaseOption (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:808:17)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:3:61)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -8:44.1.0 find-and-replace:find-previous (atom-text-editor.editor.mini.is-focused)
  2x -8:42.9.0 find-and-replace:find-next (atom-text-editor.editor.is-focused)
 20x -8:41.5.0 find-and-replace:find-previous (atom-text-editor.editor.is-focused)
     -3:25.1.0 core:cut (atom-text-editor.editor.is-focused)
     -3:24.4.0 core:paste (atom-text-editor.editor.is-focused)
     -3:24 core:save (atom-text-editor.editor.is-focused)
  2x -3:22.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:21.9.0 core:save (atom-text-editor.editor.is-focused)
     -2:06.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:03.4.0 editor:newline (atom-text-editor.editor.is-focused)
 93x -2:02.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:17.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:05.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:54.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:54.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "ignoredNames": [
      ".svn",
      ".DS_Store",
      "responsive-css/css",
      "jquery*.js"
    ],
    "openEmptyEditorOnStart": false,
    "disabledPackages": [
      "wrap-guide",
      "autoflow",
      "atom-chat"
    ]
  },
  "find-and-replace": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.14
minimap, v4.18.0
minimap-find-and-replace, v4.4.0
pigments, v0.19.3
project-manager, v2.6.5
slack-chat, v3.4.2

# Dev
No dev packages
```

**Comment by ChristopheBoucaut** [comment]
[Enter steps to reproduce below:]

* Open your atom but doesn't open a file
* Open the panel to search (ctrl + f)
* Click on a right option (see screenshot)

![bug_atom_search](https://cloud.githubusercontent.com/assets/2339969/12269208/93ad3156-b950-11e5-8edb-6b05af7eecb8.png)

**Comment by benogle** [comment]
Legit. Thanks for the steps.

**Comment by WalterGR** [comment]
Here's another way to repro.

1.  Open Atom.
2.  Open Settings -> Install.
3.  Put focus in the "Search packages" text box.
4.  Quit Atom.
5.  Open Atom.
6.  Open Find/Replace panel.
7.  Toggle "Use Regex" setting.

Blammo.

**Comment by naegi** [comment]
And another one one way to repro.
1. Open Atom 
2. Open a picture or everything which isn't text
3. Ctrl-F -> Open Find/Replace pael
4. Ctrl-Alt-/ -> Toggle "Use Regex" setting
