### ISSUE TITLE
Double clicking on result list leads to Uncaught TypeError

### ISSUE THREAD

**Issue by Yomi0** [atom/find-and-replace#650]
1. Search for a string that only occurs in one file of a project. 
2. Double click on the result list with file icon. (where the mouse is in this screenshot) ![shot-2016-01-24_00-10-34](https://cloud.githubusercontent.com/assets/3170531/12534595/f1de3a54-c22e-11e5-81c2-c40bcac797c3.png)
3. Error occurs.

**Atom Version**: 1.6.0-dev-f914d18
**System**: "Arch Linux"
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.196.0

### Stack Trace

Uncaught TypeError: _ref3.then is not a function

```
At /usr/local/share/atom/resources/app.asar/node_modules/find-and-replace/lib/project/results-view.js:52

TypeError: _ref3.then is not a function
    at space-pen-li.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/find-and-replace/lib/project/results-view.js:52:23)
    at space-pen-ol.jQuery.event.dispatch (/usr/local/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-ol.elemData.handle (/usr/local/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:28.4.0 project-find:show (atom-text-editor.editor.is-focused)
     -0:25.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "whitespace",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-hyperlink",
      "language-java",
      "language-less",
      "language-mustache",
      "language-objective-c",
      "language-javascript",
      "language-json",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-sql",
      "language-xml",
      "language-yaml"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
build, v0.52.0

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
I reproduced this using Atom v1.6.0-dev-62c1f6a on Mac OS X 10.11.2 by double-clicking on the filename when the search results were expanded:

<img width="1219" alt="uncaught-error-repro" src="https://cloud.githubusercontent.com/assets/1038121/12566524/f53575d2-c36e-11e5-893a-5af9ebcd3683.png">
