### ISSUE TITLE
Uncaught TypeError: (intermediate value) is not a function

### ISSUE THREAD

**Issue by snyderra** [atom/find-and-replace#679]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.195.0
### Stack Trace

Uncaught TypeError: (intermediate value) is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:189

TypeError: (intermediate value) is not a function
    at BufferSearch.module.exports.BufferSearch.createMarkers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:183:23)
    at BufferSearch.module.exports.BufferSearch.recreateMarkers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:168:26)
    at BufferSearch.module.exports.BufferSearch.setEditor (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:76:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find.js:73:36
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Pane.module.exports.Pane.observeActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:196:7)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:331:42
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:634:15)
    at space-pen-div.<anonymous> (/Users/robsnydermiletwo/.atom/packages/plantuml-viewer/lib/plantuml-viewer-view.js:43:48)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
  2x -5:07.2.0 editor:newline (atom-text-editor.editor.is-focused)
 12x -4:56.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:23.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:49.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:51.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:50.5.0 editor:newline (atom-text-editor.editor.is-focused)
 12x -2:40.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:32.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:30.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:22.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:06.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:01.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:44.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:35.8.0 spell-check:correct-misspelling (atom-text-editor.editor.is-focused)
  2x -0:27.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.4.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.26
plantuml-viewer, v0.7.0
script, v3.5.2

# Dev
No dev packages
```

**Comment by snyderra** [comment]
When using the plantuml-viewer plugin. create a model in a text file such as:
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml

press alt-ctl-p

click on resultant picture
