### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: //(>/: Unterminated group

### ISSUE THREAD

**Issue by dflock** [atom/find-and-replace#818]
To reproduce:

1. With a document open, enter this in the regex find box: `/(.`

**Atom Version**: 1.13.0-beta5
**Electron Version**: 1.3.9
**System**: Ubuntu 16.04.1
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package, v0.204.2

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: //(>/: Unterminated group

```
At /usr/share/atom-beta/resources/app.asar/node_modules/find-and-replace/lib/find-options.js:82

SyntaxError: Invalid regular expression: //(>/: Unterminated group
    at RegExp (native)
    at FindOptions.module.exports.FindOptions.getFindPatternRegex (/usr/share/atom-beta/resources/app.asar/node_modules/find-and-replace/lib/find-options.js:82:14)
    at BufferSearch.module.exports.BufferSearch.doesMatchTheEmptyString (/usr/share/atom-beta/resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:105:31)
    at FindView.module.exports.FindView.liveSearch (/usr/share/atom-beta/resources/app.asar/node_modules/find-and-replace/lib/find-view.js:436:139)
    at /usr/share/atom-beta/resources/app.asar/node_modules/find-and-replace/lib/find-view.js:343:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1417:25
```

### Commands

```
     -1:40.7.0 core:move-down (input.hidden-input)
     -1:40.5.0 core:confirm (input.hidden-input)
     -1:40.5.0 set-syntax:Shell Script (input.hidden-input)
     -1:38.9.0 markdown-writer:indent-list-line (input.hidden-input)
     -1:38.9.0 docblockr:parse-tab (input.hidden-input)
     -1:38.9.0 autocomplete-plus:confirm (input.hidden-input)
     -1:38.9.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -1:37.7.0 core:move-down (input.hidden-input)
 13x -1:34.4.0 core:move-right (input.hidden-input)
     -1:33 core:move-left (input.hidden-input)
  7x -1:32.5.0 core:backspace (input.hidden-input)
 10x -1:30.8.0 core:move-right (input.hidden-input)
  6x -1:11.5.0 core:backspace (input.hidden-input)
     -0:09.2.0 application:new-file (input.hidden-input)
     -0:08.9.0 core:paste (input.hidden-input)
     -0:07.5.0 find-and-replace:show (input.hidden-input)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ansible": [
        "yml"
      ],
      "source.dockerfile": [
        "m4"
      ]
    },
    "disabledPackages": [
      "robot-selenium-snippet",
      "atomatigit",
      "open-path",
      "linter-alex",
      "linter-jscs",
      "linter-jshint",
      "language-mongodb",
      "symbols-tree-view",
      "synced-sidebar",
      "indent-guide-improved"
    ],
    "ignoredNames": [
      ".git",
      ".pyc",
      ".iml",
      ".ipr",
      ".iws",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".codekit-cache",
      "bower_components",
      "node_modules"
    ],
    "packagesWithKeymapsDisabled": [
      "open-terminal-here",
      "standardjs-snippets"
    ],
    "projectHome": "/home/duncan/dev",
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
ansible-snippets, v0.2.0 (inactive)
asciidoc-assistant, v0.2.1 (active)
asciidoc-image-helper, v1.0.0 (active)
asciidoc-preview, v2.7.0 (active)
atom-alignment, v0.12.1 (active)
atom-beautify, v0.29.13 (active)
atom-dark-fusion-syntax, v1.5.1 (inactive)
atom-jinja2, v0.5.0 (active)
atom-monokai, v0.10.4 (inactive)
atom-special-char-highlighter, v0.1.0 (active)
atomatigit, v1.5.5 (inactive)
autocomplete-asciidoc, v0.1.1 (active)
autocomplete-modules, v1.6.7 (active)
autocomplete-project-paths, v2.2.0 (active)
autocomplete-python, v1.8.12 (inactive)
character-table, v0.4.3 (active)
color-picker, v2.2.3 (active)
docblockr, v0.8.7 (active)
duotone-dark-earth-syntax, v2.0.0 (inactive)
duotone-dark-forest-syntax, v2.0.0 (inactive)
duotone-dark-sea-syntax, v2.0.0 (inactive)
duotone-dark-space-syntax, v2.0.0 (inactive)
duotone-dark-syntax, v2.0.0 (inactive)
editorconfig, v2.0.5 (active)
emmet-simplified, v2.5.0 (active)
file-icons, v1.7.25 (active)
file-templates, v0.2.0 (inactive)
file-types, v0.5.4-p1 (active)
file-watcher, v0.4.0 (active)
flatwhite-syntax, v0.8.0 (inactive)
genesis-syntax, v1.0.7 (inactive)
git-blame, v0.4.11 (inactive)
git-control, v0.8.2 (inactive)
git-diff-details, v1.4.0 (active)
git-hide, v0.1.2 (active)
git-history, v3.2.0 (inactive)
git-plus, v5.25.5 (active)
git-time-machine, v1.5.4 (inactive)
hard-wrap, v1.1.0 (inactive)
indent-guide-improved, v1.4.11 (inactive)
json-converter, v0.2.4 (inactive)
language-ansible, v0.1.11 (active)
language-asciidoc, v1.6.2 (active)
language-diff, v0.6.0 (active)
language-docker, v1.1.7 (active)
language-dotfiles, v1.0.0 (active)
language-dots, v0.0.4 (active)
language-generic-config, v1.2.0 (active)
language-gradle, v0.0.3 (active)
language-groovy, v0.6.0 (active)
language-hosts, v0.1.2 (active)
language-ini, v1.16.0 (active)
language-latex, v1.0.0 (active)
language-log, v1.6.0 (active)
language-mongodb, v0.3.1 (inactive)
language-nginx, v0.6.2 (active)
language-restructuredtext, v1.0.1 (active)
language-robot-framework, v2.2.0 (active)
language-svg, v0.9.0 (active)
language-vue, v0.21.0 (active)
last-cursor-position, v0.9.0 (active)
less-than-slash, v0.16.0 (active)
linter, v1.11.20 (active)
linter-alex, v3.2.0 (inactive)
linter-ansible-syntax, v1.1.1 (active)
linter-csslint, v1.3.3 (active)
linter-js-standard, v3.6.0 (active)
linter-js-yaml, v1.2.5 (active)
linter-jscs, v4.1.0 (inactive)
linter-jshint, v3.0.1 (inactive)
linter-jsonlint, v1.3.0 (active)
linter-less, v2.6.0 (active)
linter-markdown, v3.0.2 (active)
linter-pep8, v1.3.2 (active)
linter-pydocstyle, v0.4.3 (active)
linter-sass-lint, v1.7.4 (active)
linter-shellcheck, v1.4.1 (active)
linter-swagger, v0.3.8 (active)
linter-write-good, v0.8.0 (active)
linter-xmllint, v1.3.6 (active)
markdown-themeable-pdf, v1.2.0 (active)
markdown-writer, v2.6.2 (active)
minimap, v4.26.3 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-split-diff, v0.3.2 (active)
monokai, v0.18.0 (inactive)
monokai-slate, v0.6.0 (inactive)
open-path, v0.3.6 (inactive)
open-terminal-here, v2.1.4 (inactive)
pigments, v0.38.0 (active)
pretty-json, v1.6.1 (active)
pubster-syntax, v1.4.1 (inactive)
robot-selenium-snippet, v1.0.1 (inactive)
rst-preview-pandoc, v0.1.12 (active)
set-syntax, v0.3.2 (active)
slime, v1.6.1 (inactive)
sort-lines, v0.14.0 (inactive)
split-diff, v1.0.6 (inactive)
ssh-config, v0.10.1 (active)
standardjs-snippets, v2.5.0 (inactive)
susave, v0.4.0 (inactive)
symbols-tree-view, v0.13.2 (inactive)
synced-sidebar, v0.4.3 (inactive)
tabs-closer, v0.13.0 (inactive)
text-manipulation, v0.6.0 (active)
title-case, v0.4.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
tornado-templates, v0.2.0 (active)
tree-view-git-status, v1.2.0 (active)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This will be fixed in the next beta hotfix.
