### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

### ISSUE THREAD

**Issue by jneuendorf** [atom/find-and-replace#859]
[Enter steps to reproduce:]

1. open plantUML viewer with `PlantUML Viewer > Toggle Viewer`
    - a split pane right show up
2. edit and save the plantUML source file
3. click/focus the plantUML preview

I tried debugging a little bit (until `PaneContainer.module.exports.PaneContainer.setActivePane (/app.asar/src/pane-container.js:198:22)`): It only appaers with the plantUML viewer being open but does not directly seem to be coming from the packages code.
If you find out the opposite, let me know and I will move the issue the that package.

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.206.1

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:46

TypeError: Cannot read property 'onDidStopChanging' of undefined
    at BufferSearch.setEditor (/app.asar/node_modules/find-and-replace/lib/buffer-search.js:46:48)
    at /app.asar/node_modules/find-and-replace/lib/find.js:49:36
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Pane.module.exports.Pane.observeActiveItem (/app.asar/src/pane.js:241:7)
    at /app.asar/src/pane-container.js:346:42
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/app.asar/src/pane-container.js:198:22)
    at Pane.module.exports.Pane.activate (/app.asar/src/pane.js:850:14)
    at /packages/plantuml-viewer/lib/plantuml-viewer-view.js:43:48)
    at /packages/plantuml-viewer/node_modules/jquery/dist/jquery.js:4435:9)
    at /packages/plantuml-viewer/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:27.9.0 core:save (input.hidden-input)
     -1:09.5.0 editor:newline (input.hidden-input)
     -1:08.8.0 core:save (input.hidden-input)
     -0:43.4.0 tree-view:duplicate (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:42.7.0 core:move-right (input.hidden-input)
  4x -0:42.6.0 core:move-left (input.hidden-input)
     -0:41.2.0 core:confirm (input.hidden-input)
     -0:37.9.0 core:copy (input.hidden-input)
     -0:37.3.0 core:paste (input.hidden-input)
     -0:35.3.0 core:save (input.hidden-input)
     -0:34.2.0 core:copy (input.hidden-input)
     -0:33.7.0 core:paste (input.hidden-input)
     -0:33.5.0 core:save (input.hidden-input)
  2x -0:22.6.0 core:close (input.hidden-input)
  2x -0:12.4.0 core:delete (input.hidden-input)
     -0:11.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-handlebars 1.3.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
autocomplete-paths 1.0.5 
code-annotations 2.1.3 
color-picker 2.2.5 
django-templates 0.5.0 
editorconfig 2.2.0 
emmet 2.4.3 
file-icons 2.0.15 
fold-functions 0.5.0 
highlight-line 0.12.0 
highlight-selected 0.12.0 
html-entities 0.4.0 
imdone-atom 2.1.18 
jquery-snippets 11.0.0 
language-applescript 0.3.0 
language-freemarker 0.2.0 
language-generic-config 1.3.0 
language-htaccess 0.1.1 
language-plantuml 0.2.0 
linter 1.11.22 
linter-coffeelint 1.2.1 
linter-csslint 1.3.3 
linter-erb 1.0.3 
linter-flake8 2.1.4 
linter-jshint 3.0.2 
linter-markdownlint 1.0.1 
MagicPython 1.0.6 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
minimap-selection 4.4.0 
pdf-view 0.54.0 
php-cs-fixer 4.1.0 
pigments 0.39.0 
plantuml-viewer 0.7.1 
project-manager 3.3.3 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.3 
tablr 1.8.1 
tabs-to-spaces 1.0.3 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [PlantUML](https://atom.io/packages/plantuml-viewer) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
