### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

### ISSUE THREAD

**Issue by tandriamil** [atom/find-and-replace#898]
### Description
This error showed when I created a new [plantuml viewer](https://github.com/markushedvall/plantuml-viewer) pane and moved it. After that, when I tried with another pane to see if the problem isn't due to plantuml viewer, I kept having this error and had some panes literally destroyed (atom/atom error: destroyed pane).

I restarted my editor and everything is working fine now, can't reproduce the bug any more. Note that I upgraded to Atom 1.17.0 an hour before the bug occurred, maybe it has something to do with it.

Thank you for reading this, have a nice day.

### Steps to Reproduce
1. Create a new pane or grab an opened one
2. Move it

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.207.6

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

```
At /usr/share/atom/resources/app/node_modules/find-and-replace/lib/buffer-search.js:66

TypeError: Cannot read property 'onDidStopChanging' of undefined
    at BufferSearch.setEditor (/usr/share/atom/resources/app/node_modules/find-and-replace/lib/buffer-search.js:66:1)
    at /usr/share/atom/resources/app/node_modules/find-and-replace/lib/find.js:61:1
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:129:1)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/share/atom/resources/app/src/workspace.js:489:1)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/usr/share/atom/resources/app/src/workspace-center.js:16:1)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:129:1)
    at PaneContainer.didChangeActiveItemOnPane (/usr/share/atom/resources/app/src/pane-container.js:280:1)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:318:1)
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:539:1)
    at Pane.module.exports.Pane.moveItemToPane (/usr/share/atom/resources/app/src/pane.js:655:1)
    at Object.end (/usr/share/atom/resources/app/node_modules/tabs/lib/layout.js:63:1)
    at HTMLLIElement.TabView.element.ondragend (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-view.js:62:1)
```

### Commands

```
     -0:40.4.0 intentions:highlight (input.hidden-input)
     -0:40.4.0 core:copy (input.hidden-input)
     -0:39.6.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:39.1.0 intentions:highlight (input.hidden-input)
     -0:39 core:paste (input.hidden-input)
     -0:37.9.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:35.5.0 core:confirm (input.hidden-input)
     -0:33.6.0 intentions:highlight (input.hidden-input)
     -0:33.3.0 command-palette:toggle (input.hidden-input)
     -0:32.2.0 editor:consolidate-selections (input.hidden-input)
     -0:32.2.0 core:cancel (input.hidden-input)
     -0:31.6.0 intentions:highlight (input.hidden-input)
     -0:31.4.0 command-palette:toggle (input.hidden-input)
     -0:30.7.0 editor:consolidate-selections (input.hidden-input)
     -0:30.7.0 core:cancel (input.hidden-input)
     -0:30 plantuml-viewer:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-jinja2 0.6.0 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
file-icons 2.1.6 
grammar-token-limit 0.1.1 
intentions 1.1.2 
kite 0.23.0 
language-latex 1.0.0 
language-plantuml 0.2.0 
language-restructuredtext 1.1.0 
linter 2.1.4 
linter-pylama 0.8.20 
linter-ui-default 1.5.4 
markdown-preview-enhanced 0.12.3 
markdown-table-formatter 2.9.0 
markdown-themeable-pdf 1.2.0 
minimap 4.28.2 
monokai 0.24.0 
pigments 0.39.1 
plantuml-viewer 0.7.1 
python-indent 1.0.2 
python-tools 0.6.9 
react 0.16.2 
toggle-gutter 0.3.3 
```

**Comment by midgethoen** [comment]
FYI: I'm having this issue in combination with the `plantuml-viewer` package too

**Comment by midgethoen** [comment]
Can reproduce by opening plantuml-viewer tab and focussing it

**Comment by morishift** [comment]
it also reproduced in my environment.
This is probably a problem with the current directory.
It does not reproduce if the current directory is in the same place as Atom.exe
