### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker layer

### ISSUE THREAD

**Issue by micky619** [atom/find-and-replace#961]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.209.5

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker layer

```
At C:\Users\micky_wu\AppData\Local\atom\app-1.20.1\resources\app\src\decoration-manager.js:211

Error: Cannot decorate a destroyed marker layer
    at DecorationManager.decorateMarkerLayer (~/AppData/Local/atom/app-1.20.1/resources/app/src/decoration-manager.js:211:19)
    at TextEditor.module.exports.TextEditor.decorateMarkerLayer (~/AppData/Local/atom/app-1.20.1/resources/app/src/text-editor.js:1815:43)
    at BufferSearch.setEditor (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/find-and-replace/lib/buffer-search.js:71:55)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/find-and-replace/lib/find.js:61:42
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.20.1/resources/app/src/pane-container.js:284:26)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.20.1/resources/app/src/pane-container.js:262:18)
    at Pane.module.exports.Pane.activate (~/AppData/Local/atom/app-1.20.1/resources/app/src/pane.js:919:20)
    at Pane.module.exports.Pane.focus (~/AppData/Local/atom/app-1.20.1/resources/app/src/pane.js:290:25)
    at HTMLElement.<anonymous> (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane-element.js:51:25)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.5 
chester-atom-syntax 0.3.0 
color-picker 2.2.5 
dash-ui 0.4.3 
document-outline 1.6.1 
file-icons 2.1.12 
markdown-preview-plus 2.4.10 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
minimap 4.29.7 
pdf-view 0.59.0 
split-diff 1.5.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by micky619** [comment]
Find and Repaste looks great now, but at that time I just normally find some key words but not using repaste and this issue  just appeared once. I think maybe because loading to many pages at the same time and my computer can not afford that work.

And I even don't know what is atom --safe🤔

**Comment by rsese** [comment]
ahhh ok, thanks for the details - it's helpful to know that context and that it happened once and isn't something you can reproduce.  

> And I even don't know what is atom --safe🤔

Sorry, safe mode is described in detail in the Flight Manual:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

You can start Atom in safe mode from the command line (on Windows that could be `cmd` or Powershell) by running `atom --safe`.  Atom starts with no community packages enabled so it helps us figure out if there's an issue with Atom or if an issue might be caused by a community package.

We can leave the issue open for a bit in case you or anyone else runs into the error.
