### ISSUE TITLE
Failed to activate the find-and-replace package

### ISSUE THREAD

**Issue by Mantranonymous** [atom/find-and-replace#965]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 ia32
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.212.2

### Stack Trace

Failed to activate the find-and-replace package

```
At Cannot read property 'isDestroyed' of undefined

TypeError: Cannot read property 'isDestroyed' of undefined
    at HTMLElement.ColorMarkerElement.render (/packages/pigments/lib/color-marker-element.coffee:51:48)
    at HTMLElement.ColorMarkerElement.setModel (/packages/pigments/lib/color-marker-element.coffee:42:6)
    at HTMLElement.ColorBufferElement.requestMarkerView (/packages/pigments/lib/color-buffer-element.coffee:256:10)
    at HTMLElement.ColorBufferElement.updateMarkers (/packages/pigments/lib/color-buffer-element.coffee:239:8)
    at HTMLElement.ColorBufferElement.editorConfigChanged (/packages/pigments/lib/color-buffer-element.coffee:135:6)
    at /packages/pigments/lib/color-buffer-element.coffee:93:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at StyleManager.addStyleElement (~/AppData/Local/atom/app-1.21.0/resources/app/src/style-manager.js:190:24)
    at StyleManager.addStyleSheet (~/AppData/Local/atom/app-1.21.0/resources/app/src/style-manager.js:169:18)
    at Package.module.exports.Package.activateStylesheets (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:322:64)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:246:20)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:984:31
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.0/resources/app/src/command-registry.js:353:24)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:13.6.0 find-and-replace:show (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.3.4 
atom-idiomatic-comments-css-snippets 0.1.0 
autocomplete-html-entities 0.1.0 
css-snippets 0.9.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
pigments 0.19.5 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [pigments package](https://atom.io/packages/pigments), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
